### PR TITLE
fix wrongly scrolling, add technical details

### PR DESCRIPTION
**Pull request by EaterOfCode**
@nienkedekker I added a column with a table with more technical details its ~ responsive ~

### CODE REVIEW

**Comment by nienkedekker** [comment]
lgtm!

**Comment by EaterOfCode** [comment]
is kapot :(

**Comment by nienkedekker** [comment]
?

**Comment by nienkedekker** [comment]
ooh conflicts. i'll look into it this afternoon, see if i can manually integrate your changes.

**Pull request closed without merging**
